changelog:
  categories:
    - titles:
        - Breaking Changes
        - Feature requests
        - Bug fixes
        - Other Changes
    - labels:
        - breaking-change
        - enhancements
        - bug
        - "*"
